### PR TITLE
First change

### PR DESCRIPTION
**Pull request by phukeo**
Added incorrect answer message, added correct answer message

### CODE REVIEW

**Comment by phukeo** [comment]
Hi Jonny, check out my changes and if you are happy, merge them with the master.

**Review by JonnyBloor — CHANGES_REQUESTED** [review]
when i run your code i get this in the debug console...

1: What's the secret word?
Traceback (most recent call last):
  File "c:\Users\jbloor\Desktop\Python\Ex_Files_Python_EssT\Exercise Files\Chap06\bens wile.txt", line 10, in <module>
    pw = input(f"{count}: What's the secret word?")
EOFError: EOF when reading a line

Do you get the same?

**Comment by phukeo** [comment]
> when i run your code i get this in the debug console...
> 
> 1: What's the secret word?
> Traceback (most recent call last):
> File "c:\Users\jbloor\Desktop\Python\Ex_Files_Python_EssT\Exercise Files\Chap06\bens wile.txt", line 10, in
> pw = input(f"{count}: What's the secret word?")
> EOFError: EOF when reading a line
> 
> Do you get the same?

Hi Jonny, 

No I dont get the same. But I will test your counter request which makes it work on yours and then we can merge it to the master

**Comment by JonnyBloor** [comment]
I'm just trying to understand the error, what does it mean?

**Pull request merged**
